export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'About',
  topLine2: 'Why Elrond?',
  description1: 'Frizzy is a 7777 Elrond NFT collection of cartoonish, unique, red haired character that was inspired by our baby. Frizzy has the purpose of increasing visibility of Elrond Network and act as a charity for premature born babies.',
  description2: 'Elrond NFTs are ESDTs with additional meta-data. You will be able to sell / trade your Frizzy in no time with REALLY! low fees, altough we really recommend you to HODL and be a part of our community.',
  description3: 'Elrond is what has driven us in creating Frizzy. A Romanian 🏡 startup that has built one of the most efficient blockchain technologies, with broadband performance and a massive improvement in execution speed and transaction cost.',
  imgStart: false,
  img: '/images/About_small.png',
  toplineImage1: '/images/red.png',
  toplineImage2: '/images/red.png',
  alt: 'frizzy-about',
  dark: true,
  darkText: false,
  link: false,
  marginBottom: '10px',
};

export const homeObjTwo = {
  id: 'giveaways',
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  topLine1: 'Giveaways',
  topLine2: 'Annual rewards',
  topLine3: 'BRAND NEW CAR',
  description1: 'There will be a total of 1.5k EGLD giveaways. Every 10% milestone of the project we will host a 3000$ giveaway towards 10 owners. Eariler you get, more chances to win!',
  description2: 'We will give annual rewards for members of our community, we want to intrigue you and keep it a surprise for now 🎁.',
  description3: 'After we sell out we will announce the winner of a brand new ',
  imgStart: true,
  img: '/images/car.png',
  toplineImage1: '/images/red.png',
  toplineImage2: '/images/red.png',
  toplineImage3: '/images/red.png',
  alt: 'frizzy-cats',
  dark: false,
  darkText: true,
  marginTop: '37px',
  marginBottom: '10px',
  link: true,
  linkHref: '//www.tesla.com/modelx',
  linkDescription: 'Tesla Model X.'
};

export const homeObjThree = {
  id: 'perks',
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  topLine1: 'Future development and marketing',
  topLine2: 'Giveaways',
  topLine3: 'Donation',
  description2: 'We love helping who helped us, therefore we will be giving 30% of the profit back to you guys. Every minting milestone we will hold a giveaway session for owners, the earlier you get in, the more chances 😄 !',
  description3: 'Our hearts are driven on helping the little ones that may have a chance at life, therefore owning a Frizzy will make you part of it 🎅🎁. The money will go towards the following ',
  description1: 'This money will be used for our future NFT project and on marketing Frizzy forward all around social media to increase visibility.',
  imgStart: false,
  img: '/images/Chart_small1.png',
  imgWidth: '93%',
  toplineImage1: '/images/blue.png',
  toplineImage2: '/images/yellow.png',
  toplineImage3: '/images/pink.png',
  alt: 'frizzy-chart',
  primary: false,
  darkText: true,
  link: true,
  linkHref: '//www.asociatiaprematurilor.ro/',
  linkDescription: 'premature babies NGO.',
  marginBottom: '90px',
};

export const homeObjFour = {
  id: 'perks',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'Future airdrops',
  topLine2: 'Merchandise',
  topLine3: 'Royalties',
  description1: 'We will be creating more projects, the early adopters will receive free future art & other giveaways from us 👀.',
  description2: 'We are planning on creating different merchandise (colouring books, educational baby cards, T-shirts, 3D printed Frizzy), also a game in the upcoming years. We will also donate part of the money from merchandise sales 🎁.',
  description3: '5% of the royalties from the secondary market will be used for floor swiping and 5% will be donated towards ',
  imgStart: true,
  img: '/images/Santa_small.png',
  toplineImage1: '/images/red.png',
  toplineImage2: '/images/red.png',
  toplineImage3: '/images/red.png',
  alt: 'frizzy-santa',
  primary: true,
  darkText: false,
  marginTop: '37px',
  marginBottom: '10px',
  link: true,
  linkHref: '//www.asociatiaprematurilor.ro/',
  linkDescription: 'the same NGO.'
};
