export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'About',
  topLine2: 'Why Elrond?',
  description1: 'Frizzy is a 7777 NFT collection of cartoonish, unique, red haired character that was inspired by our toddler. The art used in creating the project is composed out of 140 different hand drawn elements.',
  description2: 'Elrond NFTs are ESDTs with additional metadata. You will be able to sell / trade your Frizzy in no time with REALLY! low fees, although we really recommend you to HODL and be a part of our community as we strive to bring value to holders every day.',
  description3: 'Elrond is a Romanian 🏡 startup that has built one of the most efficient blockchain technologies, with broadband performance and a massive improvement in execution speed and transaction cost.',
  imgStart: false,
  img: '/images/About_small.png',
  toplineImage1: '/images/red.png',
  toplineImage2: '/images/red.png',
  alt: 'frizzy-about',
  dark: true,
  darkText: false,
  link: false,
  click: false,
  marginBottom: '10px',
};

export const homeObjTwo = {
  id: 'giveaways',
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  topLine1: 'Giveaways',
  topLine2: 'Annual rewards',
  topLine3: 'BRAND NEW CAR',
  description1: 'We will have a total of 1000 $EGLD giveaways. The more Frizzies you own, the more chances to win!',
  description2: 'We will host annual rewards for the most active members of our community, we want to intrigue you and keep it a surprise for now 🎁.',
  description3: 'At sell out 1 out of the 25 Frizzy owners with the car accessory trait will get a brand new ',
  imgStart: true,
  img: '/images/car.png',
  toplineImage1: '/images/red.png',
  toplineImage2: '/images/red.png',
  toplineImage3: '/images/red.png',
  alt: 'frizzy-cats',
  dark: false,
  darkText: true,
  marginTop: '37px',
  marginBottom: '10px',
  link: false,
  click: true,
  linkHref: '//www.tesla.com/model3',
  linkDescription: '🚗'
};

export const homeObjThree = {
  id: 'perks',
  lightBg: true,
  lightText: false,
  lighttextDesc: false,
  topLine1: 'Future development and marketing',
  topLine2: 'Giveaways',
  topLine3: 'Donation',
  description2: 'We love helping who helped us, therefore we will constantly develop value to give back to the community. We will hold giveaway sessions every 5% milestone and we created an $LKMEX farm that generates monthly salary 😄 !',
  description3: 'Our hearts are driven on helping the little ones that might have a chance at life, owning a Frizzy NFT will make you part of it 💖🎅🎁. Every 10% of the milestone we will make a donation.',
  description1: 'We will use part of the income towards art drops, marketing, creating merchandise and developing the game.',
  imgStart: false,
  img: '/images/Chart_small1.png',
  imgWidth: '93%',
  toplineImage1: '/images/blue.png',
  toplineImage2: '/images/yellow.png',
  toplineImage3: '/images/pink.png',
  alt: 'frizzy-chart',
  primary: false,
  darkText: true,
  link: true,
  click: false,
  linkHref: '//www.asociatiaprematurilor.ro/',
  linkDescription: 'premature babies NGO.',
  marginBottom: '90px',
};

export const homeObjFour = {
  id: 'perks',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'Art drops',
  topLine2: 'Become a brand',
  topLine3: 'Royalties',
  description1: 'We are having NFT art drops weekly & early access for owners on other NFT project called "Magic Realms Cards"',
  description2: 'We will work on creating illustrated books, educational baby cards, T-shirts and more. Part of merchandise will go towards different foster houses that need a bit of hope 🎁.\n After minting we will start developing a child friendly play-to-earn game! ',
  description3: 'For now, the royalties will go into the $LKMEX farm, after minting they will go towards ',
  imgStart: true,
  img: '/images/Santa_small.png',
  toplineImage1: '/images/red.png',
  toplineImage2: '/images/red.png',
  toplineImage3: '/images/red.png',
  alt: 'frizzy-santa',
  primary: true,
  darkText: false,
  marginTop: '37px',
  marginBottom: '10px',
  link: true,
  click: false,
  linkHref: '//www.asociatiaprematurilor.ro/',
  linkDescription: 'premature babies NGO.'
};
