export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'About',
  topLine2: 'Why MultiversX?',
  description1: 'Frizzy is an NFT collection  with 7777 NFTs of cartoonish, unique, red haired character that was inspired by our toddler (mom & dad). The art used in creating the project is composed out of 140+ different hand drawn elements.',
  description2: 'MultiversX NFTs are ESDTs with additional metadata. You will be able to trade your NFTs really fast and with very low fees, although we would love if you would becomee a part of our community as we strive to bring value to holders gradually.',
  description3: 'MultiversX is a Romanian startup that has built one of the most efficient blockchain technologies, with broadband performance and a massive improvement in execution speed and transaction cost.',
  imgStart: false,
  img: '/images/About_small.png',
  toplineImage1: '/images/blue.png',
  toplineImage2: '/images/red.png',
  alt: 'frizzy-about',
  darkText: false,
  link: false,
  click: false,
  marginBottom: '10px',
};

export const homeObjThree = {
  id: 'perks',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'Passive income',
  topLine2: 'Giveaways',
  topLine3: 'Donation',
  description2: 'We like surprising people, so every now and then we will host raffles, giveaways and game nights with different prizes for our NFT holders;',
  description3: 'Our hearts are driven on helping the little ones in need that might have a chance at life, owning a Frizzy NFT will make you part of it as 30% of every Frizzy sale will go towards ',
  description1: 'We have an ongoing EGLD-LKMEX LP farm that is generating ~8M LKMEX / month. Every month we distribute this sum towards our holders based on their roles in the Discord;',
  imgStart: true,
  img: '/images/Victor.png',
  imgWidth: '110%',
  toplineImage1: '/images/blue.png',
  toplineImage2: '/images/yellow.png',
  toplineImage3: '/images/pink.png',
  alt: 'frizzy-and-victor',
  primary: true,
  darkText: false,
  link: true,
  click: false,
  linkHref: '//www.togetherforvictor.ro/',
  linkDescription: 'Victors cause.',
  marginBottom: '90px',
};

export const homeObjFour = {
  id: 'brand',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine1: 'Become a brand',
  topLine2: 'Children books',
  topLine3: 'Royalties',
  description1: 'We are working on spreading Frizzy around the world with different assets, physical or digital. Our dream is that one day, kids will play with Frizzy toys!',
  description2: 'We started creating children books and selling them worldwide through Amazon KDP. Soon we will have a PDF Viewer where you will be able to read the book digitally here on the website based on your book NFT',
  description3: '70% of royalties are distributed back into developing the project further, while 30% are going towards ',
  imgStart: false,
  video: '/images/treasure.mp4',
  toplineImage1: '/images/blue.png',
  toplineImage2: '/images/red.png',
  toplineImage3: '/images/yellow.png',
  alt: 'frizzy-santa',
  primary: true,
  darkText: false,
  marginTop: '37px',
  marginBottom: '10px',
  link: true,
  click: false,
  linkHref: '//www.togetherforvictor.ro/',
  linkDescription: 'Victor.'
};
